#region LICENSE
/*
    ZXSinclair Emulador ZX Computers make in .Net and .Net CORE
    Copyright (C) 2016 Oscar Hernandez Bano
    This file is part of ZXSincalir.Net.
    ZXSincalir.Net is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.*/
#endregion

using System.Text;
using ZXSinclair.Net.Generate.Z80OpCodes.Model;
using ZXSinclair.Net.Generate.Z80OpCodes.Patterns;

namespace ZXSinclair.Net.Generate.Z80OpCodes.Emit;

internal sealed record EmittedOpcode(Opcode Opcode, bool Implemented, string Body);
internal sealed record GeneratedDispatch(OpcodeTableKind Table, string FileName, string Text, EmittedOpcode[] Opcodes);

internal static class DispatchEmitter
{
    public static GeneratedDispatch[] Generate(IReadOnlyDictionary<OpcodeTableKind, Opcode[]> tables, PatternCatalog catalog) =>
        Enum.GetValues<OpcodeTableKind>().Select(table => Emit(table, tables, catalog)).ToArray();

    private static GeneratedDispatch Emit(OpcodeTableKind table,
        IReadOnlyDictionary<OpcodeTableKind, Opcode[]> tables, PatternCatalog catalog)
    {
        var (file, signature) = table switch
        {
            OpcodeTableKind.Base => ("Z80Cpu.Main.g.cs", "ExecuteMain(byte opcode)"),
            OpcodeTableKind.CB => ("Z80Cpu.CB.g.cs", "ExecuteCB(byte opcode)"),
            OpcodeTableKind.ED => ("Z80Cpu.ED.g.cs", "ExecuteED(byte opcode)"),
            OpcodeTableKind.DDFD => ("Z80Cpu.Indexed.g.cs", "ExecuteIndexedOpcode<TIndex>(byte opcode) where TIndex : struct, IIndexRegister"),
            OpcodeTableKind.DDFDCB => ("Z80Cpu.IndexedCB.g.cs", "ExecuteIndexedCB<TIndex>(ushort address, byte opcode) where TIndex : struct, IIndexRegister"),
            _ => throw new ArgumentOutOfRangeException(nameof(table)),
        };
        var emitted = new List<EmittedOpcode>();
        foreach (var original in tables[table].OrderBy(o => o.Byte))
        {
            var opcode = original;
            if (table == OpcodeTableKind.DDFD && opcode.Kind == OpcodeKind.Absent)
                opcode = tables[OpcodeTableKind.Base][opcode.Byte] with { Table = table };
            // Prefix decoding belongs exclusively to the handwritten CPU loop.
            if (opcode.Kind == OpcodeKind.Prefix || table == OpcodeTableKind.DDFD && opcode.Byte is 0xCB or 0xDD or 0xED or 0xFD)
            {
                emitted.Add(new(opcode with { Kind = OpcodeKind.Prefix }, false, ""));
                continue;
            }
            var pattern = catalog.Resolve(opcode);
            var body = pattern is null ? "" : SourceFormat.Normalize(pattern.EmitBody(opcode, new(table))).Trim();
            emitted.Add(new(opcode, pattern is not null, body));
        }
        var lines = new StringBuilder();
        lines.AppendLine(SourceFormat.Normalize(SourceFormat.LicenseHeader).Replace("\n", Environment.NewLine));
        lines.AppendLine();
        lines.AppendLine("// <auto-generated>");
        lines.AppendLine("// Generated by ZXSinclair.Net.Generate.Z80OpCodes. Do not edit by hand.");
        lines.AppendLine("#nullable enable");
        lines.AppendLine();
        lines.AppendLine("namespace ZXSinclair.Net.Core.Z80;");
        lines.AppendLine();
        lines.AppendLine("public sealed partial class Z80Cpu<TBus>");
        lines.AppendLine("{");
        if (table == OpcodeTableKind.Base)
            lines.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        lines.AppendLine($"    private void {signature}");
        lines.AppendLine("    {");
        // Keep the empty NOP path independent of the growing jump table.
        if (table == OpcodeTableKind.Base && emitted.Any(e => e.Opcode.Byte == 0 && e.Implemented && e.Body.Length == 0))
        {
            lines.AppendLine("        if (opcode == 0) return;");
            lines.AppendLine("        ExecuteMainDispatch(opcode);");
            lines.AppendLine("    }");
            lines.AppendLine();
            // The small wrapper can inline into Step regardless of the switch's IL size.
            lines.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
            lines.AppendLine("    private void ExecuteMainDispatch(byte opcode)");
            lines.AppendLine("    {");
        }
        lines.AppendLine("        switch (opcode)");
        lines.AppendLine("        {");
        var groups = emitted.Where(e => e.Implemented).GroupBy(e => (e.Body, e.Opcode.Comment))
            .OrderBy(g => g.Min(e => e.Opcode.Byte));
        foreach (var group in groups)
        {
            var items = group.OrderBy(e => e.Opcode.Byte).ToArray();
            foreach (var item in items[..^1])
                lines.AppendLine($"            case 0x{item.Opcode.Byte:x2}:");
            var last = items[^1];
            var bodyLines = group.Key.Body.Split('\n');
            if (table == OpcodeTableKind.Base && group.Key.Body.Length != 0)
            {
                lines.AppendLine($"            case 0x{last.Opcode.Byte:x2}: ExecuteMain{last.Opcode.Byte:X2}(); return; // {group.Key.Comment}");
                continue;
            }
            if (bodyLines.Length == 1)
                lines.AppendLine($"            case 0x{last.Opcode.Byte:x2}: {(group.Key.Body.Length == 0 ? "" : group.Key.Body + " ")}{(table == OpcodeTableKind.Base ? "return" : "break")}; // {group.Key.Comment}");
            else
            {
                lines.AppendLine($"            case 0x{last.Opcode.Byte:x2}: // {group.Key.Comment}");
                lines.AppendLine("            {");
                foreach (var line in bodyLines) lines.AppendLine("                " + line);
                lines.AppendLine("                break;");
                lines.AppendLine("            }");
            }
        }
        lines.AppendLine("            default: Unimplemented(); break;");
        lines.AppendLine("        }");
        lines.AppendLine("    }");
        if (table == OpcodeTableKind.Base)
        {
            foreach (var group in groups.Where(g => g.Key.Body.Length != 0))
            {
                var value = group.Max(e => e.Opcode.Byte);
                lines.AppendLine();
                lines.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
                lines.AppendLine($"    private void ExecuteMain{value:X2}()");
                lines.AppendLine("    {");
                foreach (var line in group.Key.Body.Split('\n'))
                    lines.AppendLine("        " + line);
                lines.AppendLine("    }");
            }
        }
        lines.AppendLine("}");
        return new(table, file, lines.ToString(), emitted.ToArray());
    }
}
