#region LICENSE
/*
    ZXSinclair Emulador ZX Computers make in .Net and .Net CORE
    Copyright (C) 2016 Oscar Hernandez Bano
    This file is part of ZXSincalir.Net.
    ZXSincalir.Net is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.*/
#endregion



using System.Text;
using ZXSinclair.Net.Generate.Z80OpCodes.Model;

namespace ZXSinclair.Net.Generate.Z80OpCodes.Emit;

internal sealed record GeneratedSource(string FileName, string Text);

internal static class Im0TableEmitter
{
    public static byte[] BuildBits(GeneratedDispatch main)
    {
        var bits = new byte[32];
        foreach (var item in main.Opcodes)
        {
            // Only single-byte opcodes can run from the acknowledge byte without reading through PC.
            if (!item.Implemented || item.Opcode.Kind == OpcodeKind.Prefix || item.Opcode.Length != 1)
                continue;
            bits[item.Opcode.Byte >> 3] |= (byte)(1 << (item.Opcode.Byte & 7));
        }
        return bits;
    }

    public static GeneratedSource Emit(GeneratedDispatch main)
    {
        var text = new StringBuilder();
        text.AppendLine(SourceFormat.Normalize(SourceFormat.LicenseHeader).Replace("\n", Environment.NewLine));
        text.AppendLine();
        text.AppendLine("// <auto-generated>");
        text.AppendLine("// Generated by ZXSinclair.Net.Generate.Z80OpCodes. Do not edit by hand.");
        text.AppendLine("#nullable enable");
        text.AppendLine();
        text.AppendLine("namespace ZXSinclair.Net.Core.Z80;");
        text.AppendLine();
        text.AppendLine("public sealed partial class Z80Cpu<TBus>");
        text.AppendLine("{");
        text.AppendLine("    private static ReadOnlySpan<byte> Im0SingleByteOpcodes =>");
        text.AppendLine("    [");
        var bits = BuildBits(main);
        for (var i = 0; i < bits.Length; i += 8)
            text.AppendLine("        " + string.Join(", ", bits.Skip(i).Take(8).Select(b => $"0x{b:X2}")) + ",");
        text.AppendLine("    ];");
        text.AppendLine();
        text.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        text.AppendLine("    private static bool IsIm0SingleByte(byte opcode) =>");
        text.AppendLine("        (Im0SingleByteOpcodes[opcode >> 3] & (1 << (opcode & 7))) != 0;");
        text.AppendLine("}");
        return new("Z80Cpu.Im0.g.cs", text.ToString());
    }

    public static GeneratedSource[] Sources(GeneratedDispatch[] dispatches) =>
        [.. dispatches.Select(d => new GeneratedSource(d.FileName, d.Text)),
            Emit(dispatches.Single(d => d.Table == OpcodeTableKind.Base))];
}
